### ISSUE TITLE
Warning: Cannot modify header information - headers already sent 

### ISSUE THREAD

**Issue by matallana** [cryptomkt/woocommerce-plugin#1]
Hi,

im using the plugin on woocommerce, but also using the transbank webpay from chile too,
then the checkout block is disabled, unless i turn off the plugin,
the debug show me the php headers trouble:

Notice: Undefined index: REQUEST_SCHEME in /home/comercon/public_html/tienda/wp-content/plugins/woocommerce-transbank/libwebpay/healthcheck.php on line 50

Warning: Cannot modify header information - headers already sent by (output started at /home/comercon/public_html/tienda/wp-content/plugins/cryptomarket-for-woocommerce/class-wc-gateway-criptomarket.php:1) in /home/comercon/public_html/tienda/wp-content/plugins/woocommerce-transbank/libwebpay/loghandler.php on line 384

![sin titulo](https://user-images.githubusercontent.com/20309866/43362274-5f891062-92b4-11e8-8ba6-1b1f05b60d5e.png)

**Comment by mariopando** [comment]
Please try update the plugin with last release version, if problems persist just contact us on this channel.

**Comment by matallana** [comment]
now it works but return me a api 401

![image](https://user-images.githubusercontent.com/20309866/43902489-394c8110-9bb8-11e8-998e-320d3930a5e9.png)


"Client error: `POST https://api.cryptomkt.com/v1/payment/new_order` resulted in a `401 Unauthorized` response: {"status": "error", "message": "authentication_error"}"

i dont know if my config is correct but let me share a screenshot with cryptomkt panel and below the woocommerce config.

![image]()

**Comment by mariopando** [comment]
Check that credentials are correct, copying and pasting the information provided, 401 Error means that credentials are wrong or renew your api keys from you CryptoMarket Account.


P.D: Please be careful providing images that contain sensible information (API Key, API Secret)
