### ISSUE TITLE
Tengo el sitio en USD 

### ISSUE THREAD

**Issue by Lbenza** [cryptomkt/woocommerce-plugin#2]
Se puede hacer para ser compatible con USD?

**Comment by Goro2030** [comment]
Parece que no?

**Comment by mariopando** [comment]
> Se puede hacer para ser compatible con USD?

Es una característica que incluiremos en nuestro Backlog, puesto que requiere consultar un servicio que ofrezca valores USD, que perdure en el tiempo y que no tenga costos asociados para mantener el nivel de gratuidad que ofrece el plugin, si tienes una propuesta a nivel de código será muy bienvenida.

**Comment by Goro2030** [comment]
Hay miles de API's de exchange rates ... o un query a finance.google.com para resolver USDCLP
