### ISSUE TITLE
Critical Error - No Genera la orden de pago porque tira un error critico en una clase

### ISSUE THREAD

**Issue by tocho2020** [cryptomkt/woocommerce-plugin#3]
CRITICAL Object of class stdClass could not be converted to string in /home/….../……./wp-content/plugins/cryptomarket-for-woocommerce/class-wc-gateway-criptomarket.php on line 493

**Comment by tocho2020** [comment]
testeado en versión Woocommerce 4.1.1 y WP 5.4.1

**Comment by mariopando** [comment]
@tocho2020 que version del plugin usas? la ultima esta [aqui](https://github.com/cryptomkt/woocommerce-plugin/releases/tag/0.2.3), recrearemos un ambiente con lo indicado para detectar el problema, gracias por tu tiempo

**Comment by tocho2020** [comment]
he descargado la versión 0.2.3 pero en WordPress sigue diciendo 0.1.1 y eso que instalé desde cero.
si quieres puedes probar lo que sucede en este site

https://xboxgiftmarket.com/

pones comprar y pagar con BTC y no genera la parte del invoice tirando un error que no especifica cual es.

**Comment by tocho2020** [comment]
en Firefox si se ve y dice Internal Server Error.

**Comment by mariopando** [comment]
Resueltos los problemas de manejo de strings, el patch está aplicado en https://github.com/cryptomkt/woocommerce-plugin/releases/tag/0.2.5, de antemano agradecemos el feedback de la comunidad para lograr una solución de mejor calidad :)
